name:                hwc
version:             0.1.0.0
github:              "0xd34df00d/hwc"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2020 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            The common Unix wc command, in Haskell, faster than GNU coreutils'
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/hwc#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- bytestring-mmap
- optparse-applicative
- template-haskell

ghc-options:
- -fllvm
- -O2
- -Wall

library:
  source-dirs: src

executables:
  hwc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-A2m
    dependencies:
    - hwc

tests:
  hwc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hwc
    - hspec
    - hspec-core
    - QuickCheck
    - text
